require_relative 'user'
require 'csv'
require 'faker'
require 'pg'

class ThirdParty
  def self.get_infos
    { name: Faker::Name.name, identities: {
      Faker::Internet.uuid => {
        email: Faker::Internet.email
      },
      Faker::Internet.uuid => {
        email: Faker::Internet.email
      },
    }}
  end
end

# Debugging
# ActiveRecord::Base.logger = Logger.new(STDOUT)

task :migrate do
  ActiveRecord::Schema.define do
    create_table :users, force: true do |t|
      t.string :full_name
      t.jsonb :thirdparty_infos, default: {}, null: false
    end
    
    # CREATE INDEX idx_users_identities_keys ON users USING gin ((thirdparty_infos->'identities'));
    add_index :users, "((thirdparty_infos->'identities'))", using: :gin
  end
end

task :import_csv do
  users = []
  # Ensure the CSV file exists
  file = './shared/seed.csv'
  unless File.exist?(file)
    raise "CSV file not found"
  end

  CSV.foreach(file, encoding: 'utf-8', headers: true, skip_blanks: true, col_sep: ',').with_index(1) do |row, index|
    user = { full_name: row['full_name'], thirdparty_infos: ThirdParty.get_infos }
    users << user
  end

  ActiveRecord::Base.transaction do
    users.each do |user|
      User.create!(user)
    end
  end

  # Inject custom UUID
  random_index = rand(users.length)
  custom_infos = { name: Faker::Name.name, identities: {
      "itachiuchihadekonoha": {
        email: "does not matter"
      },
      "notmatter": {
        email: "does not matter"
      }
    }
  }
  
  user = User.find(random_index)
  user.update(thirdparty_infos: custom_infos, full_name: "renegado")
  
  puts "Inject user with uuid: itachiuchihadekonoha at index #{random_index}"
end
